
name: My First Action

on: push  # Runs when code is pushed

jobs:
  my-job: #Here you put the name of the job
    runs-on: ubuntu-latest # The CI-CD pipeline will run on Ubuntu
    steps:
      - name: Checkout code
        run: git clone https://github.com/berezovsky13/nodejs.git  # Gets the latest code, in other words it does 'git clone' 
      - name: Print Hello World
        run: echo "Hello, GitHub Actions!" # This is just the command
      - name: Ping Google
        run: ping -c 4 8.8.8.8
      - name: Check Ping Results # Optional: Check if the ping was successful
        run: |
          if [[ $? -eq 0 ]]; then # Check the exit code of the ping command
            echo "Ping to Google was successful!"
          else
            echo "Ping to Google failed!"
            exit 1 # Optional: Fail the workflow if the ping fails
          fi
